import type { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'



export default function HomePage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Github Repo Search
        </h1>

        <p className={styles.description}>
          在下方欄位輸入要搜尋的使用者名稱
        </p>

        <input className={styles.text_field} type="text" placeholder="例如： SnowFireWolf" />

        <button className={styles.button}>
          搜尋
        </button>
      </main>

      <footer className={styles.footer}>
        Kevin Zheng 2022
      </footer>
    </div>
  )
}



export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {}
  }
}